language: r
cache: packages

before_install:
  - sudo apt-get install tk8.5 tcl8.5

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true 
  
